service: serverless-telegram-mustashinizer

plugins:
  - serverless-offline
custom:
  config: ${file(.env.yml):${opt:stage, self:provider.stage}}
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  memorySize: 128
  timeout: 15
  endpointType: regional
  environment:
    region: ${self:provider.region}
functions:
  telegramEventHandler:
    handler: api/telegram.eventHandler
    description: Handle events from telegram
    events:
      - http:
          path: webhook
          method: post
          cors: true
    environment:
      bot_token: ${self:custom.config.bot_token}